language: java

jdk:
  - openjdk11

jobs:
  include:
    - stage: compile
      script: "./gradlew build -x test"
    - stage: test
      script: "./gradlew test"
    - stage: release
      script: "./gradlew bintrayUpload"
      if: branch = master and tag is present
    - stage: deploy
      script: skip
      if: branch = master
      deploy: &heroku
        provider: heroku
        app: markov-chain-service
        api_key:
          secure: D0hdSyhT1Yug7iLup9fZU9quznMEsAzOX0CltAk5Ghpdz5AK6EdxrluIuRuynzfA/4s/GKM8VY1uYE2DSp9XYuHx8hHPKUcjLBWocJ4iLc9fMulwKuaX4JIItx8NRVgBoRKDgpoDLv+akCsvm1XMWSSg93OM/itaBCR5gpK/MY4AzvVQHJI/Ff5w9VkT2vriqjTkVzQufdkZB27gALyjRHg/okA+eT5UH4LQ4zYkRnbFdXNWgA7h9uFIBn4/3f1SJ9rVXx7LJnNB4TxOS1F0mOP+SGTbpEs+53Ona3R2xLZEooR/8x/XOfulV8jsRUrxLZaTE6sBr+cEwcr81a2Z7whio64XkmtuP3x58VTTWxgVVPlyrZCiVVDP/dboBurrRjNKpJ2mrSyE54sdkIjGunPm+FnLzYVaALp3Hueyzj2LBmDc8lzm9+Afxdc4KpKcZQ7fwZ4OnIFh/PjCgRIg2zcxiD+hAD15S9aDLimZ8rKtMWm+6erg6mnF6A2p11QptSTWiwK+PLwlyHcgXh1blejkI4lLCWvYgngWm2882I1S8BSLWJ6H00IsuDjxO9/KgXLLDqd/7BtCwZkQj7oH8/78f0pR+tMHvm+dFRfru1zHt7zu7UGHjJt4xCUb6QZGSkOg4sdLAso+5uVA1srKcvBt5jEkhgU3TpJOUcrUyYk=

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
